# Generated by Django 3.0.6 on 2020-06-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('p', 'In-Progress'), ('n', 'New'), ('na', 'Invalid'), ('d', 'Done')], default='n', max_length=10),
        ),
    ]
